### ISSUE TITLE
[DataScienceSchool] <Python Libs.> 3. 데이터 탐색

### ISSUE THREAD

**Issue by qus0in** [qus0in/colab#7]
# 데이터 사이언스 스쿨
## 파이썬
* [링크](https://datascienceschool.net/view-notebook/39569f0132044097a15943bd8f440ca5/)
### 데이터 탐색
- [x] Pandas 패키지의 소개 #4 ([링크](https://datascienceschool.net/view-notebook/ee0a5679dd574b94b55193690992f850))
- [x] 데이터 입출력 #5 ([링크](https://datascienceschool.net/view-notebook/c5ccddd6716042ee8be3e5436081778b))
- [x] 데이터프레임 고급 인덱싱 #6 ([링크](https://datascienceschool.net/view-notebook/704731b41f794b8ea00768f5b0904512))
- [x] 데이터프레임의 데이터 조작 #13 ([링크](https://datascienceschool.net/view-notebook/aa62265f02fc429aa636ef343c3b1fda))
- [x] 데이터프레임 인덱스 조작 #15 ([링크](https://datascienceschool.net/view-notebook/a49bde24674a46699639c1fa9bb7e213))
- [x] 데이터프레임 합성 #16 ([링크](https://datascienceschool.net/view-notebook/7002e92653434bc88c8c026c3449d27b)) 
- [x] 피봇테이블과 그룹분석 #17 ([링크](https://datascienceschool.net/view-notebook/76dcd63bba2c4959af15bec41b197e7c))
- [ ] 시계열 자료 다루기 ([링크](https://datascienceschool.net/view-notebook/8959673a97214e8fafdb159f254185e9))
